/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tema1_apostolstefan;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.Timer;
import javax.swing.ImageIcon;
import tema1_apostolstefan.Agenda.CriteriuOrdonare;



/**
 *
 * @author Apostol
 */
public class GUI extends javax.swing.JFrame {

    private DefaultListModel<Contact> model = new DefaultListModel<Contact>();    //LISTA GRAFICA pt a afisa agenda in interfata grafica
    private DefaultComboBoxModel filtre = new DefaultComboBoxModel(new String[]{"NR_FIX", "NR_MOBIL", "NASCUTI_ZI_CURENTA", "NASCUTI_LUNA_CURENTA", "PERSONALIZAT"});
    private DefaultComboBoxModel ordoneaza = new DefaultComboBoxModel(new String[]{"DUPA_NUME", "DUPA_PRENUME", "DUPA_VARSTA", "DUPA_TELEFON"});
    public String filtru;
    public Agenda a = new Agenda();
    ImageIcon imaginea;
    String[] imagini = {"1.jpg", "2.jpg", "3.jpg", "4.jpg"};  
    int index = 0; //index pentru a parcuge imaginile
    
    ActionListener task = new ActionListener() {  //definirea unui actionlistener pt timer
        @Override
        public void actionPerformed(ActionEvent ae) {  //metoda de schimbare a imagini... dupa o perioada a timer ului
            if (index == 4) {  //resetarea buclei 
                index = 0;
            } else {

                imaginea = new ImageIcon(getClass().getResource(imagini[index])); 
                poza.setIcon(imaginea);   
                index++;  //trecerea la urmatoarea reclama
            }

        }
    };
    javax.swing.Timer timer = new javax.swing.Timer(1000, task);    //schimba reclama la 1 secunda

    private void actualizeazaModel(List m) {  //functie care actualizeaza lista grafica cu Agenda
        model.clear();
        for (int i = 0; i < m.size(); i++) {  
            Contact k = (Contact) m.get(i);
            model.addElement(k);
        }
    }

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        cbf.setModel(filtre);       //setarea listei grafice cu metodele de filtrare
        cbo.setModel(ordoneaza);    //setarea listei grafice cu metodele de ordonare
        bAdaugare.setEnabled(false);     //blocarea butoanelor pentru modul oaspete
        bStergere.setEnabled(false);     //blocarea butoanelor pentru modul oaspete
        bEditeaza.setEnabled(false);     //blocarea butoanelor pentru modul oaspete
        bFiltreaza.setEnabled(false);    //blocarea butoanelor pentru modul oaspete
        bOrdoneaza.setEnabled(false);    //blocarea butoanelor pentru modul oaspete
        cbf.setEnabled(false);           //blocarea butoanelor pentru modul oaspete
        cbo.setEnabled(false);           //blocarea butoanelor pentru modul oaspete
        tf2.setEnabled(false);           //blocarea butoanelor pentru modul oaspete
        mbSalvare.setEnabled(false);     //blocarea butoanelor pentru modul oaspete
        mbDeschidere.setEnabled(false);  //blocarea butoanelor pentru modul oaspete
        timer.start();             //pornirea timerului pentru reclame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Adaugare_contacte = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bAdauga = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Stergere = new javax.swing.JDialog();
        nu = new javax.swing.JButton();
        da = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        element_desters = new javax.swing.JLabel();
        Modificare_contacte = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        bModifica = new javax.swing.JButton();
        dialog_iesire = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fc = new javax.swing.JFileChooser();
        fc2 = new javax.swing.JFileChooser();
        Despre = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Inregistrare = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        parola = new javax.swing.JTextField();
        bInregistreaza = new javax.swing.JButton();
        bine_venit = new javax.swing.JDialog();
        incarca = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bFiltreaza = new javax.swing.JButton();
        bOrdoneaza = new javax.swing.JButton();
        bAdaugare = new javax.swing.JButton();
        bEditeaza = new javax.swing.JButton();
        bStergere = new javax.swing.JButton();
        label_filtrare = new javax.swing.JLabel();
        label_ordonare = new javax.swing.JLabel();
        cbf = new javax.swing.JComboBox<>();
        cbo = new javax.swing.JComboBox<>();
        label_filtru = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        l = new javax.swing.JList<>();
        tf2 = new javax.swing.JTextField();
        poza = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_fisier = new javax.swing.JMenu();
        mbSalvare = new javax.swing.JMenuItem();
        mbDeschidere = new javax.swing.JMenuItem();
        mbIesire = new javax.swing.JMenuItem();
        menu_ajutor = new javax.swing.JMenu();
        mbInregistrare = new javax.swing.JMenuItem();
        mbDespre = new javax.swing.JMenuItem();

        jLabel1.setText("Nume");

        jLabel2.setText("Prenume");

        jLabel3.setText("Data_nastere");

        jLabel4.setText("Telefon");

        bAdauga.setText("Adauga");
        bAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdaugaActionPerformed(evt);
            }
        });

        jLabel5.setText("ADAUGARE  CONTACTE");

        javax.swing.GroupLayout Adaugare_contacteLayout = new javax.swing.GroupLayout(Adaugare_contacte.getContentPane());
        Adaugare_contacte.getContentPane().setLayout(Adaugare_contacteLayout);
        Adaugare_contacteLayout.setHorizontalGroup(
            Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Adaugare_contacteLayout.createSequentialGroup()
                .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Adaugare_contacteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bAdauga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Adaugare_contacteLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4))))
                .addContainerGap())
            .addGroup(Adaugare_contacteLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel5)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        Adaugare_contacteLayout.setVerticalGroup(
            Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Adaugare_contacteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(Adaugare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(bAdauga, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        Stergere.setModal(true);

        nu.setText("NU");
        nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuActionPerformed(evt);
            }
        });

        da.setText("DA");
        da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daActionPerformed(evt);
            }
        });

        jLabel6.setText("Sunteti siguri ca doriti sa stergeti elementul selectat?");

        javax.swing.GroupLayout StergereLayout = new javax.swing.GroupLayout(Stergere.getContentPane());
        Stergere.getContentPane().setLayout(StergereLayout);
        StergereLayout.setHorizontalGroup(
            StergereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StergereLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(da, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(nu, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(StergereLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(StergereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(element_desters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StergereLayout.setVerticalGroup(
            StergereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StergereLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(element_desters, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(StergereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nu)
                    .addComponent(da))
                .addGap(31, 31, 31))
        );

        jLabel7.setText("Modificare Contact");

        jLabel8.setText("Nume nou:");

        jLabel9.setText("Prenume nou:");

        jLabel10.setText("Data nastere noua:");

        jLabel11.setText("Telefon nou:");

        bModifica.setText("Modifica");
        bModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Modificare_contacteLayout = new javax.swing.GroupLayout(Modificare_contacte.getContentPane());
        Modificare_contacte.getContentPane().setLayout(Modificare_contacteLayout);
        Modificare_contacteLayout.setHorizontalGroup(
            Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificare_contacteLayout.createSequentialGroup()
                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Modificare_contacteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Modificare_contacteLayout.createSequentialGroup()
                                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField5)))
                            .addGroup(Modificare_contacteLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))))
                    .addGroup(Modificare_contacteLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Modificare_contacteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField8))
                    .addGroup(Modificare_contacteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bModifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Modificare_contacteLayout.setVerticalGroup(
            Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificare_contacteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Modificare_contacteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(bModifica)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel13.setText("Doriti sa parasiti aplicatia?");

        jButton1.setText("DA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("NU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_iesireLayout = new javax.swing.GroupLayout(dialog_iesire.getContentPane());
        dialog_iesire.getContentPane().setLayout(dialog_iesireLayout);
        dialog_iesireLayout.setHorizontalGroup(
            dialog_iesireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_iesireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_iesireLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(114, 114, 114))
        );
        dialog_iesireLayout.setVerticalGroup(
            dialog_iesireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_iesireLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialog_iesireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("          DESPRE AUTOR SI APLICATIE\n\n-AUTOR:  APOSTOL STEFAN MIHAI\n-APLICATIE: AGENDA TELEFONICA\n-PAROLA APLICATIE: \"12345\"");
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout DespreLayout = new javax.swing.GroupLayout(Despre.getContentPane());
        Despre.getContentPane().setLayout(DespreLayout);
        DespreLayout.setHorizontalGroup(
            DespreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        DespreLayout.setVerticalGroup(
            DespreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jLabel12.setText("INTRODUCE PAROLA");

        bInregistreaza.setText("Inregistreaza");
        bInregistreaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInregistreazaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InregistrareLayout = new javax.swing.GroupLayout(Inregistrare.getContentPane());
        Inregistrare.getContentPane().setLayout(InregistrareLayout);
        InregistrareLayout.setHorizontalGroup(
            InregistrareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InregistrareLayout.createSequentialGroup()
                .addGroup(InregistrareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InregistrareLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel12)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addGroup(InregistrareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InregistrareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bInregistreaza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parola))))
                .addContainerGap())
        );
        InregistrareLayout.setVerticalGroup(
            InregistrareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InregistrareLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(parola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bInregistreaza)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        incarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout bine_venitLayout = new javax.swing.GroupLayout(bine_venit.getContentPane());
        bine_venit.getContentPane().setLayout(bine_venitLayout);
        bine_venitLayout.setHorizontalGroup(
            bine_venitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bine_venitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bine_venitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(incarca, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bine_venitLayout.setVerticalGroup(
            bine_venitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bine_venitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(incarca, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bFiltreaza.setText("Filtreaza");
        bFiltreaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltreazaActionPerformed(evt);
            }
        });

        bOrdoneaza.setText("Ordoneaza");
        bOrdoneaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdoneazaActionPerformed(evt);
            }
        });

        bAdaugare.setText("Adaugare Contact");
        bAdaugare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdaugareActionPerformed(evt);
            }
        });

        bEditeaza.setText("Editeaza contact selectat");
        bEditeaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditeazaActionPerformed(evt);
            }
        });

        bStergere.setText("Stergere contact selectat");
        bStergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStergereActionPerformed(evt);
            }
        });

        label_filtrare.setText("Filtrare:");

        label_ordonare.setText("Ordonare:");

        cbf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NUMAR_FIX", "NUMAR_MOBIL", "NASCUTI_ZI_CURENTA", "NASCUTI_LUNA_CURENTA", "PERSONALIZAT" }));
        cbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfActionPerformed(evt);
            }
        });

        cbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DUPA_NUME", "DUPA_PRENUME", "DUPA_VARSTA", "DUPA_DATA" }));

        label_filtru.setText("Filtru:");

        l.setBackground(new java.awt.Color(215, 225, 255));
        jScrollPane1.setViewportView(l);

        menu_fisier.setText("Fisiere");
        menu_fisier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_fisierActionPerformed(evt);
            }
        });

        mbSalvare.setText("Salvare");
        mbSalvare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbSalvareActionPerformed(evt);
            }
        });
        menu_fisier.add(mbSalvare);

        mbDeschidere.setText("Deschidere");
        mbDeschidere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbDeschidereActionPerformed(evt);
            }
        });
        menu_fisier.add(mbDeschidere);

        mbIesire.setText("Iesire");
        mbIesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbIesireActionPerformed(evt);
            }
        });
        menu_fisier.add(mbIesire);

        jMenuBar1.add(menu_fisier);

        menu_ajutor.setText("Ajutor");

        mbInregistrare.setText("Inregistrare");
        mbInregistrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbInregistrareActionPerformed(evt);
            }
        });
        menu_ajutor.add(mbInregistrare);

        mbDespre.setText("Despre");
        mbDespre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbDespreActionPerformed(evt);
            }
        });
        menu_ajutor.add(mbDespre);

        jMenuBar1.add(menu_ajutor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(poza, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_filtrare)
                                    .addComponent(label_ordonare))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(label_filtru)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bOrdoneaza, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(bFiltreaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bAdaugare, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(bStergere, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(bEditeaza, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bFiltreaza)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_filtrare)
                        .addComponent(cbf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_filtru)
                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOrdoneaza)
                    .addComponent(label_ordonare)
                    .addComponent(cbo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAdaugare)
                    .addComponent(bStergere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEditeaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(poza, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAdaugareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdaugareActionPerformed
        Adaugare_contacte.setVisible(true);   //afisare tab adaugare
        Adaugare_contacte.pack();             //redimensionare tab adaugare
    }//GEN-LAST:event_bAdaugareActionPerformed

    private void bAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdaugaActionPerformed

        try {
            String nume = jTextField1.getText();
            String prenume = jTextField2.getText();
            String data = jTextField3.getText();
            String telefon = jTextField4.getText();
            a.Adauga(nume, prenume, data, telefon);   //adaugarea noului contact in Agenda
            l.setModel(model);   //actualizarea listei grafica (Modelul)
            actualizeazaModel(a.Contacte);
            Adaugare_contacte.setVisible(false);  //inchiderea tab-ului de adaugare.
        } catch (RuntimeException e) {  //PROPAGAREA  ERORILOR LA ADAUGARE.
            if (e.getMessage().equals("NUMELE SAU PRENUMELE PREA SCURT!")) {
                JOptionPane.showMessageDialog(this, "NUMELE SAU PRENUMELE PREA SCURT!");
            }
            if (e.getMessage().equals("contactul exista!")) {
                JOptionPane.showMessageDialog(this, "CONTACTUL EXISTA DEJA IN LISTA DE CONTACTE!");
            }
            if (e.getMessage().contains("parse")) {
                JOptionPane.showMessageDialog(this, "PROBLEMA LA FORMATUL DATEI zz/ll/yyyy!");
            }
            if (e.getMessage().contains("Numaru nu are 10 cifre...")) {
                JOptionPane.showMessageDialog(this, "NUMARUL NU ARE 10 CIFRE!");
            }
            if (e.getMessage().contains("Numarul nu incepe cu 07,02 sau 03!")) {
                JOptionPane.showMessageDialog(this, "NUMARUL DE TELEFON NU INCEPE CU 07,02 sau 03!");
            }
        }
    }//GEN-LAST:event_bAdaugaActionPerformed

    private void bStergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStergereActionPerformed
        Stergere.setVisible(true);   //afisarea panoului cu "Sunteti siguri ca veti sterge?"
        Stergere.pack();               //redimensionarea tabului de dialog Stergere
    }//GEN-LAST:event_bStergereActionPerformed

    private void nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuActionPerformed
        Stergere.setVisible(false);     //inchide tab ul de stergere
    }//GEN-LAST:event_nuActionPerformed

    private void daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daActionPerformed
        int selectedIndex = l.getSelectedIndex();   //obtine index ul elementului de sters
        if (selectedIndex != -1) {           //verificare index invalid
            model.remove(selectedIndex);     //eliminam elementul din model
            a.Stergere((Contact) a.Contacte.get(selectedIndex)); //stergem contactul din agenda
            Stergere.setVisible(false);     //inchidem tab ul de dialog Stergere
        }
    }//GEN-LAST:event_daActionPerformed

    private void bFiltreazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltreazaActionPerformed
        int selectedIndex = cbf.getSelectedIndex();       //obtinem indicele curent din lista grafica de filtrari
        if (selectedIndex == 0) { //dupa numar fix; 
            a.filtreazaNrFix();          //setam campul de filtrare
            List contacte_filtrate = a.contacte_functie(0);   //apelam metoda de filtrare
            actualizeazaModel(contacte_filtrate);         //actualizarea listei cu contactele filtrate
        }
        if (selectedIndex == 1) { //dupa numar mobil;    
            a.filtreazaNrMobil();                     //setam campul de filtrare
            List contacte_filtrate = a.contacte_functie(0);   //apelam metoda de filtrare
            actualizeazaModel(contacte_filtrate);        //actualizarea listei cu contactele filtrate
        }
        if (selectedIndex == 2) { //dupa nascuti in ziua asta;
            a.filtreazaNascutiAstazi();          //setam campul de filtrare
            List contacte_filtrate = a.contacte_functie(0);    //apelam metoda de filtrare
            actualizeazaModel(contacte_filtrate);           //actualizarea listei cu contactele filtrate
        }

        if (selectedIndex == 3) { //dupa numar luna;
            a.filtreazaNascutiLunaCurenta();      //setam campul de filtrare
            List contacte_filtrate = a.contacte_functie(0);
            actualizeazaModel(contacte_filtrate);           //actualizarea listei cu contactele filtrate
        }
        if (selectedIndex == 4) { //personalizat
            filtru = tf2.getText();                 //scoatem text ul scris in tf2 pentru a il cauta in lista de contacte
            a.filtreazaPersonalizat(filtru);            //setam campul de filtrare
            List contacte_filtrate = a.contacte_functie(0);  //apelam metoda de filtrare
            actualizeazaModel(contacte_filtrate);                   //actualizarea listei cu contactele filtrate
        }
    }//GEN-LAST:event_bFiltreazaActionPerformed

    private void bOrdoneazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdoneazaActionPerformed
        int selectedIndex = cbo.getSelectedIndex();  //obtinem indicele curent din lista grafica de filtrari
        if (selectedIndex == 0) { //dupa nume
            a.Ordoneaza(CriteriuOrdonare.DUPA_NUME);  //setarea campului de ordonare
            List contacte_filtrate = a.contacte_functie(1);  //ordonarea dupa nume(apelararea metodei contacte_functie(1))
            actualizeazaModel(contacte_filtrate);
        }
        if (selectedIndex == 1) { //dupa prenume
            a.Ordoneaza(CriteriuOrdonare.DUPA_PRENUME);  //setarea campului de ordonare
            List contacte_filtrate = a.contacte_functie(1);  //ordonarea dupa prenume(apelararea metodei contacte_functie(1))
            actualizeazaModel(contacte_filtrate);
        }
        if (selectedIndex == 2) { //dupa varsta
            a.Ordoneaza(CriteriuOrdonare.DUPA_VARSTA);   
            List contacte_filtrate = a.contacte_functie(1);
            actualizeazaModel(contacte_filtrate);
        }
        if (selectedIndex == 3) { //dupa telefon
            a.Ordoneaza(CriteriuOrdonare.DUPA_TELEFON);
            List contacte_filtrate = a.contacte_functie(1);
            actualizeazaModel(contacte_filtrate);
        }
    }//GEN-LAST:event_bOrdoneazaActionPerformed

    private void bEditeazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditeazaActionPerformed
        Modificare_contacte.setVisible(true);   //afisarea tab ului de modificare contacte
        Modificare_contacte.pack();             //redimensionarea acestui tab

    }//GEN-LAST:event_bEditeazaActionPerformed

    private void bModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificaActionPerformed

        try {
            int selectedIndex;
            String nume = jTextField5.getText();
            String prenume = jTextField6.getText();                       //initializarea datelor
            String data = jTextField7.getText();
            String telefon = jTextField8.getText();
            selectedIndex = l.getSelectedIndex();
            Contact c = (Contact) a.Contacte.get(selectedIndex);   //crearea contactului
            a.Modifica(nume, prenume, data, telefon, c);           //modificarea contactului initial cu cel nou in agenda
            actualizeazaModel(a.Contacte);                        //actualizarea listei grafice a agendei
            Modificare_contacte.setVisible(false);                //inchiderea tab ului de modificare
        } catch (RuntimeException e) {
            if (e.getMessage().equals("NUMELE SAU PRENUMELE PREA SCURT!")) {
                JOptionPane.showMessageDialog(this, "NUMELE SAU PRENUMELE PREA SCURT!");
            }
            if (e.getMessage().equals("contactul exista!")) {
                JOptionPane.showMessageDialog(this, "CONTACTUL EXISTA DEJA IN LISTA DE CONTACTE!");
            }
            if (e.getMessage().contains("parse")) {
                JOptionPane.showMessageDialog(this, "PROBLEMA LA FORMATUL DATEI zz/ll/yyyy!");
            }
            if (e.getMessage().contains("Numaru nu are 10 cifre...")) {
                JOptionPane.showMessageDialog(this, "NUMARUL NU ARE 10 CIFRE!");
            }
            if (e.getMessage().contains("Numarul nu incepe cu 07,02 sau 03!")) {
                JOptionPane.showMessageDialog(this, "NUMARUL DE TELEFON NU INCEPE CU 07,02 sau 03!");
            }
        }


    }//GEN-LAST:event_bModificaActionPerformed

    private void mbInregistrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbInregistrareActionPerformed
        Inregistrare.setVisible(true);   //afisarea tab ului de Inregistrare    
        Inregistrare.pack();            //redimensionarea acestui tab
    }//GEN-LAST:event_mbInregistrareActionPerformed

    private void mbDespreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbDespreActionPerformed
        Despre.setVisible(true);     //afisarea tab ului cu informatii aplicatie
        Despre.pack();             //redimensionarea acestui tab
    }//GEN-LAST:event_mbDespreActionPerformed

    private void mbIesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbIesireActionPerformed
        dialog_iesire.setVisible(true);   //afisarea Dialogului de Iesire din aplicatie 
        dialog_iesire.pack();           //redimensionarea acestui tab
    }//GEN-LAST:event_mbIesireActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dialog_iesire.setVisible(false);      //inchiderea Dialogului de Iesire in caz ca a fost apasat "NU"
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);         //iesirea din aplicatie in cazul in care a fost apasat "DA"
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mbSalvareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbSalvareActionPerformed
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {  //deschiderea tabului de salvare
            File f = fc.getSelectedFile();   //selectarea fisierului
            Timer t = new Timer();   //setarea timer ului de autosalvare
            TimerTask task = new TimerTask() {
                @Override
                public void run() {
                    try {
                        FileOutputStream fos = new FileOutputStream(f);    //salvarea
                        ObjectOutputStream oos = new ObjectOutputStream(fos);  //salvarea
                        oos.writeObject(a.Contacte);   //scrierea agendei
                        oos.close();   //inchiderea fiserului de iesire
                        fos.close();
                    } catch (IOException ex) {
                        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            };
            t.schedule(task, 0, 60000);   //porinrea timer ului de salvare automata la 1 minut
        }
    }//GEN-LAST:event_mbSalvareActionPerformed

    private void menu_fisierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_fisierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_fisierActionPerformed

    private void mbDeschidereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbDeschidereActionPerformed
        if (fc2.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { //deschiderea tabului de deschidere
            File f = fc2.getSelectedFile();   //selecatea fisierului care trebuie deschis
            try {
                FileInputStream fis = new FileInputStream(f);
                ObjectInputStream ois = new ObjectInputStream(fis);   //deschiderea 
                a.Contacte = (List) ois.readObject();  //citirea agendei
                fis.close();
                ois.close(); //inchiderea
            } catch (IOException iOException) {
                JOptionPane.showMessageDialog(this, "Eroare la citire");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            l.setModel(model);  //setarea modelului in caz ca nu exista contacte.
            actualizeazaModel(a.Contacte);  //actualizarea modelului.
        }
    }//GEN-LAST:event_mbDeschidereActionPerformed

    private void cbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfActionPerformed

    }//GEN-LAST:event_cbfActionPerformed

    private void bInregistreazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInregistreazaActionPerformed
        String parolaa;
        parolaa = parola.getText();
        if (parolaa.equals("12345")) {  //daca parola se potriveste
            bAdaugare.setEnabled(true);   //deblocarea butoanelor
            bStergere.setEnabled(true);
            bEditeaza.setEnabled(true);
            bFiltreaza.setEnabled(true);  //deblocarea butoanelor
            bOrdoneaza.setEnabled(true);
            cbf.setEnabled(true);   //deblocarea butoanelor
            cbo.setEnabled(true);
            tf2.setEnabled(true);
            mbSalvare.setEnabled(true);    //deblocarea butoanelor
            mbDeschidere.setEnabled(true); //deblocarea butoanelor
            Inregistrare.setVisible(false);   
            mbInregistrare.setEnabled(false);
            timer.stop();   //oprirea timer ului cu reclame
            poza.setVisible(false);   //stergerea reclamei
            JOptionPane.showMessageDialog(this, "PAROLA CORECTA!");   //afisarea Dialog bucurie...

        } else {
            JOptionPane.showMessageDialog(this, "PAROLA GRESITA!");  //afisare Dialog neecaz...
        }

    }//GEN-LAST:event_bInregistreazaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Adaugare_contacte;
    private javax.swing.JDialog Despre;
    private javax.swing.JDialog Inregistrare;
    private javax.swing.JDialog Modificare_contacte;
    private javax.swing.JDialog Stergere;
    private javax.swing.JButton bAdauga;
    private javax.swing.JButton bAdaugare;
    private javax.swing.JButton bEditeaza;
    private javax.swing.JButton bFiltreaza;
    private javax.swing.JButton bInregistreaza;
    private javax.swing.JButton bModifica;
    private javax.swing.JButton bOrdoneaza;
    private javax.swing.JButton bStergere;
    private javax.swing.JDialog bine_venit;
    private javax.swing.JComboBox<String> cbf;
    private javax.swing.JComboBox<String> cbo;
    private javax.swing.JButton da;
    private javax.swing.JDialog dialog_iesire;
    private javax.swing.JLabel element_desters;
    private javax.swing.JFileChooser fc;
    private javax.swing.JFileChooser fc2;
    private javax.swing.JLabel incarca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JList<Contact> l;
    private javax.swing.JLabel label_filtrare;
    private javax.swing.JLabel label_filtru;
    private javax.swing.JLabel label_ordonare;
    private javax.swing.JMenuItem mbDeschidere;
    private javax.swing.JMenuItem mbDespre;
    private javax.swing.JMenuItem mbIesire;
    private javax.swing.JMenuItem mbInregistrare;
    private javax.swing.JMenuItem mbSalvare;
    private javax.swing.JMenu menu_ajutor;
    private javax.swing.JMenu menu_fisier;
    private javax.swing.JButton nu;
    private javax.swing.JTextField parola;
    private javax.swing.JLabel poza;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
